[package]
name = "primitives"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapsize = "0.4"
rustc-hex = "2"
byteorder = "1.0"
bigint = "4.4.3"
